spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.13.163:3306/springbootMybatis
    driver-class-name: com.mysql.jdbc.Driver
#    initialization-mode: always
    schema:
      - classpath:Person.sql
server:
  port: 8080