spring:
  datasource:
    #基本属性设置
    username: root
    password: 123456
    url: jdbc:mysql://192.168.13.163:3306/springbootMybatis
    driver-class-name: com.mysql.jdbc.Driver
#    initialization-mode: always
#        schema:
#          - classpath:Person.sql
    ###################以下为druid增加的配置##################
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，此处是filter修改的地方
      filters: stat, wall, log4j
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
###########################JPA###########################
  jpa:
    hibernate:
      # 更新或者创建数据表
      ddl-auto: update
    # 控制台显示sql
    show-sql: true

###########################整合mybatis配置文件类型###########################
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

#infocore.staremer.name=jack
#infocore.staremer.message=nihao